project:
  type: book
  output-dir: ../docs

book:
  title: "Introduction to Machine Learning and Deep Learning"
  author: "Maximilian Pichler and Florian Hartig"
  date: "Oct 2022"
  repo-url: https://github.com/MaximilianPi/Pichler-and-Hartig-2022
  repo-branch: master
  repo-actions: [edit]
  chapters:
    - index.qmd
    - elastic_net.qmd
    - svm.qmd
    - knn.qmd
    - rf.qmd
    - brt.qmd
    - dnn.qmd
    - cnn.qmd
    - rnn.qmd
    - gnn.qmd
  appendices: 
    - refs.qmd

bibliography: references.bib
google-scholar: true

execute:
  freeze: auto
  cache: false

format:
  html:
    theme: cosmo
editor: visual
